# Hugo自動ビルド・デプロイワークフロー
# このワークフローは以下の場合に実行されます：
# 1. mainブランチにコンテンツ関連ファイルがプッシュされた時
# 2. GitHubのActionsタブから手動で実行された時
# 
# ワークフローの動作：
# - リポジトリをチェックアウト（サブモジュール含む）
# - Hugoをセットアップ
# - サイトをビルド
# - ビルドされたサイトをmainブランチのdocsディレクトリにコミット
# - GitHub Pagesはmainブランチのdocsディレクトリから配信

name: Hugo Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'  # contentディレクトリの変更時のみ実行
      - 'static/**'   # 静的ファイルの変更時も実行
      - 'layouts/**'  # レイアウトの変更時も実行
      - 'config.toml' # 設定ファイルの変更時も実行
  workflow_dispatch:  # 手動実行のためのトリガー

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Update site content [skip ci]" || echo "No changes to commit"
          git push
